pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    
    stages {
        stage('Checkout'){
            steps{
                git 'https://github.com/swatisudipta/test_project'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
